#!/bin/bash
# Updated by Manoot for Zabbix Version 1.8.3 and 1.8.4 
# ChangeLog:
# Added missing dependencies and updated for newer versions of zabbix.

# ZABBIX INSTALL SCRIPT
# VER. 0.6.4 - http://blog.brendon.com
# Copyright (c) 2008-2010 Brendon Baumgartner
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#
#=====================================================================